# Generated by Django 5.2.4 on 2025-08-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivicTrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved')], max_length=20),
        ),
    ]
